const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

/**
 * Generate a campaign summary PDF report
 */
const generateCampaignReport = async (data) => {
  return new Promise((resolve, reject) => {
    try {
      const uploadsDir = path.join(__dirname, '..', 'uploads', 'reports');
      if (!fs.existsSync(uploadsDir)) {
        fs.mkdirSync(uploadsDir, { recursive: true });
      }

      const filename = `report_${Date.now()}.pdf`;
      const filePath = path.join(uploadsDir, filename);
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      // Header
      doc.fontSize(24).fillColor('#6366f1').text('CRM Agency Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor('#64748b').text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(1);

      // Divider
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e2e8f0');
      doc.moveDown(1);

      // Report Title
      if (data.title) {
        doc.fontSize(18).fillColor('#1e293b').text(data.title);
        doc.moveDown(0.5);
      }

      // Client Info
      if (data.clientName) {
        doc.fontSize(14).fillColor('#475569').text(`Client: ${data.clientName}`);
        doc.moveDown(0.5);
      }

      // Summary Stats
      if (data.summary) {
        doc.moveDown(0.5);
        doc.fontSize(16).fillColor('#1e293b').text('Performance Summary');
        doc.moveDown(0.5);

        const stats = [
          { label: 'Total Spend', value: `$${data.summary.totalSpend || 0}` },
          { label: 'Impressions', value: (data.summary.totalImpressions || 0).toLocaleString() },
          { label: 'Clicks', value: (data.summary.totalClicks || 0).toLocaleString() },
          { label: 'CTR', value: `${data.summary.ctr || 0}%` },
          { label: 'CPC', value: `$${data.summary.cpc || 0}` },
          { label: 'Conversions', value: (data.summary.totalConversions || 0).toLocaleString() },
        ];

        stats.forEach(stat => {
          doc.fontSize(11).fillColor('#64748b').text(`${stat.label}: `, { continued: true });
          doc.fillColor('#1e293b').text(stat.value);
        });
      }

      // Campaigns Table
      if (data.campaigns && data.campaigns.length > 0) {
        doc.moveDown(1);
        doc.fontSize(16).fillColor('#1e293b').text('Campaign Details');
        doc.moveDown(0.5);

        data.campaigns.forEach((campaign, idx) => {
          doc.fontSize(12).fillColor('#6366f1').text(`${idx + 1}. ${campaign.name}`);
          doc.fontSize(10).fillColor('#64748b')
            .text(`   Status: ${campaign.status} | Budget: $${campaign.budget} | Spend: $${campaign.spend}`)
            .text(`   Impressions: ${campaign.impressions} | Clicks: ${campaign.clicks} | CTR: ${campaign.ctr}%`);
          doc.moveDown(0.3);
        });
      }

      // Footer
      doc.moveDown(2);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e2e8f0');
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor('#94a3b8').text('This report was auto-generated by CRM Agency SaaS Platform', { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve({
          filePath,
          fileUrl: `/uploads/reports/${filename}`,
          filename
        });
      });

      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateCampaignReport };
