import { useState, useEffect } from 'react';
import { DataTable } from '../../components/DataTable';
import { FileText, Download, Calendar, Filter, Target } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { reportService } from '../../services/reportService';
import toast from 'react-hot-toast';
import { formatDate } from '../../utils/formatters';

const ReportsPage = () => {
  const { activeWorkspace } = useAuth();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchReports();
  }, [activeWorkspace]);

  const fetchReports = async () => {
    try {
      if (activeWorkspace) {
        const res = await reportService.getReports(activeWorkspace);
        setReports(res.data);
      }
    } catch (error) {
      console.error('Failed to fetch reports');
    }
  };

  const handleGenerateReport = async () => {
    try {
      setLoading(true);
      await reportService.generateReport({ 
        workspaceId: activeWorkspace,
        title: 'Monthly Performance Review',
        type: 'campaign_summary'
      });
      toast.success('Report generated successfully');
      fetchReports();
    } catch (error) {
      toast.error('Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const handleExportLeads = async () => {
    try {
      await reportService.exportLeadsCSV(activeWorkspace);
      toast.success('Leads exported successfully');
    } catch (error) {
      toast.error('Failed to export leads');
    }
  };

  const columns = [
    { 
      header: 'Report Name', 
      accessor: 'title',
      cell: (row) => (
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-indigo-500/20 flex items-center justify-center text-indigo-400">
            <FileText size={20} />
          </div>
          <div>
            <p className="font-medium text-white">{row.title}</p>
            <p className="text-xs text-crm-textMuted uppercase tracking-wider">{row.type.replace('_', ' ')}</p>
          </div>
        </div>
      )
    },
    { 
      header: 'Generated By', 
      accessor: (row) => row.generatedBy?.name || 'System',
    },
    { 
      header: 'Date', 
      accessor: 'createdAt',
      cell: (row) => formatDate(row.createdAt)
    },
    { 
      header: 'Status', 
      accessor: 'status',
      cell: (row) => (
        <span className={row.status === 'ready' ? 'badge-active' : 'badge-warning'}>
          {row.status}
        </span>
      )
    },
    {
      header: 'Actions',
      sortable: false,
      cell: (row) => (
        row.fileUrl && (
          <a 
            href={`${import.meta.env.VITE_API_URL || 'http://localhost:5005'}${row.fileUrl}`}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-crm-primary/10 text-crm-primary hover:bg-crm-primary/20 transition-colors text-sm font-medium"
          >
            <Download size={16} /> Download
          </a>
        )
      )
    }
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Reports & Analytics</h1>
          <p className="text-crm-textMuted text-sm mt-1">Generate and download performance reports.</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleExportLeads}
            className="glass-button-secondary"
          >
            <Download size={18} />
            Export Leads CSV
          </button>
          <button 
            onClick={handleGenerateReport}
            disabled={loading}
            className="glass-button"
          >
            <FileText size={18} />
            {loading ? 'Generating...' : 'Generate PDF Report'}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card p-6 border-l-4 border-l-indigo-500">
          <div className="w-10 h-10 rounded-lg bg-indigo-500/10 flex items-center justify-center text-indigo-400 mb-3">
            <Calendar size={20} />
          </div>
          <h3 className="font-semibold text-white">Monthly Summary</h3>
          <p className="text-sm text-crm-textMuted mt-1">Comprehensive overview of all campaigns, spend, and leads across clients.</p>
        </div>
        <div className="glass-card p-6 border-l-4 border-l-emerald-500">
          <div className="w-10 h-10 rounded-lg bg-emerald-500/10 flex items-center justify-center text-emerald-400 mb-3">
            <Target size={20} />
          </div>
          <h3 className="font-semibold text-white">Campaign Analytics</h3>
          <p className="text-sm text-crm-textMuted mt-1">Detailed performance metrics for individual active campaigns.</p>
        </div>
        <div className="glass-card p-6 border-l-4 border-l-violet-500">
          <div className="w-10 h-10 rounded-lg bg-violet-500/10 flex items-center justify-center text-violet-400 mb-3">
            <Filter size={20} />
          </div>
          <h3 className="font-semibold text-white">Custom Report</h3>
          <p className="text-sm text-crm-textMuted mt-1">Filter by date ranges, specific clients, and selected metrics.</p>
        </div>
      </div>

      <div className="mt-8">
        <h3 className="text-lg font-bold text-white mb-4">Generated Reports Archive</h3>
        <DataTable 
          columns={columns} 
          data={reports} 
          searchPlaceholder="Search reports by name..."
        />
      </div>
    </div>
  );
};

export default ReportsPage;
