import React, { useEffect, useRef } from 'react';
import { Dialog, DialogTitle, DialogContent, DialogActions, Button, Box, Typography } from '@mui/material';
import { Html5QrcodeScanner } from 'html5-qrcode';

const QRScannerModal = ({ open, onClose, onScanSuccess }) => {
  const scannerRef = useRef(null);

  useEffect(() => {
    if (open) {
      const scanner = new Html5QrcodeScanner(
        "qr-reader",
        { fps: 10, qrbox: { width: 250, height: 250 } },
        /* verbose= */ false
      );

      scanner.render((decodedText) => {
        onScanSuccess(decodedText);
        scanner.clear();
      }, (error) => {
        // console.warn(error);
      });

      scannerRef.current = scanner;
    }

    return () => {
      if (scannerRef.current) {
        scannerRef.current.clear().catch(err => console.error("Failed to clear scanner", err));
      }
    };
  }, [open, onScanSuccess]);

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="xs" PaperProps={{ sx: { borderRadius: 3 } }}>
      <DialogTitle sx={{ fontWeight: 700 }}>Scan Workspace QR</DialogTitle>
      <DialogContent>
        <Typography variant="body2" sx={{ color: '#718096', mb: 2 }}>
          Point your camera at the workspace QR code generated by your admin.
        </Typography>
        <Box id="qr-reader" sx={{ width: '100%', overflow: 'hidden', borderRadius: 2 }}></Box>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 3 }}>
        <Button onClick={onClose} color="inherit">Cancel</Button>
      </DialogActions>
    </Dialog>
  );
};

export default QRScannerModal;
